apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: autosd-app-template
  title: AutoSD Sample Application
  description: Applications that demonstrate how typical automotive applications use SOME/IP to talk to each other.
  tags:
    - automotive
    - autosd
    - jumpstarter
    - cpp
spec:
  owner: automotive
  type: service
  parameters:
    - title: Provide Project Information
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          default: autosd-app
          description: Unique name of the project
          ui:field: EntityNamePicker
          maxLength: 23
        description:
          title: Description
          type: string
          default: Applications that demonstrate how typical automotive applications use SOME/IP to talk to each other.
          description: Help others understand what this build is for.

  steps:
    - id: request-url
      name: Get cluster URL
      action: http:backstage:request
      input:
        method: GET
        path: /catalog/entities/by-name/template/default/autosd-app-template
        headers:
          Accept-Encoding: identity

    - id: extract-url
      name: Extract cluster URL
      action: roadiehq:utils:jsonata
      input:
        data: ${{ steps['request-url'].output.body }}
        expression: metadata.annotations."backstage.io/source-location"

    - id: parse-url
      name: Parse cluster URL
      action: regex:replace
      input:
        regExps:
          - pattern: (?:.*cluster-)(\w{5})(?:.*)
            replacement: $1
            values:
              - key: guid
                value: ${{ steps['extract-url'].output.result }}
          - pattern: (?:.*)(cluster-\w{5}.*\.com)(?:.*)
            replacement: $1
            values:
              - key: base_domain
                value: ${{ steps['extract-url'].output.result }}

    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: ${{ user.entity.metadata.name }}-${{ parameters.component_id }}-build
          # namespace: ${{ parameters.component_id }}-build
          owner: ${{ user.entity.metadata.name }}
          cluster: .apps.${{ steps['parse-url'].output.values.base_domain }}
          #cluster: .apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          host: gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}
          #host: gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          destination: ${{ user.entity.metadata.name }}/${{ parameters.component_id }}
          #destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          jumpstarter_host: grpc.apps.${{ steps['parse-url'].output.values.base_domain }}:443
          #jumpstarter_host: grpc.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}:443
          registry_host: quay-${{ steps['parse-url'].output.values.guid }}.apps.${{ steps['parse-url'].output.values.base_domain }}
          #registry_host: quay-${{ parameters.guid }}.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          #registry_destination: ${{ user.entity.metadata.name }}/${{ parameters.component_id }}
          registry_destination: ${{ user.entity.metadata.name }}/${{ parameters.component_id }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.component_id}}"
        #repoUrl: "gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.component_id}}"
        #repoUrl: "gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        title: code resources for ${{ parameters.component_id }}
        defaultBranch: main
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: template-gitops-deployment
      name: Generating Deployment Resources
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: https://gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}-gitops.git
          #destination: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}-gitops.git
          #destination: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ parameters.repo.owner }}/${{parameters.component_id}}-gitops.git
          source_repository: https://gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}.git
          #source_repository: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}.git
          #source_repository: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ parameters.repo.owner }}/${{parameters.component_id}}.git
          source_repository_pac: https://gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}
          #source_repository_pac: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ user.entity.metadata.name }}/${{parameters.component_id}}
          #source_repository_pac: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ parameters.repo.owner }}/${{parameters.component_id}}
          gitlab_url: https://gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}/
          #gitlab_url: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/
          repository_name: ${{parameters.component_id}}
          git_owner: ${{ user.entity.metadata.name }}
          #git_owner: ${{ parameters.repo.owner }}
          cluster: .apps.${{ steps['parse-url'].output.values.base_domain }}
          #cluster: .apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          namespace: ${{ user.entity.metadata.name }}-${{ parameters.component_id }}-dev
          image_registry: "Quay"
          jumpstarter_host: grpc.apps.${{ steps['parse-url'].output.values.base_domain }}:443
          #jumpstarter_host: grpc.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}:443
          registry_host: quay-${{ steps['parse-url'].output.values.guid }}.apps.${{ steps['parse-url'].output.values.base_domain }}
          #registry_host: quay-${{ parameters.guid }}.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          #registry_organization: ${{ user.entity.metadata.name }}
          registry_organization: ${{ user.entity.metadata.name }}
          image_name: ${{ parameters.component_id }}
          image_tag: latest
          repository_host: gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}
          #repository_host: gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}
          deployment_name: ${{ parameters.component_id }}
          user: ${{ user.entity.metadata.name }}
        targetPath: ./tenant-gitops

    - id: publish-gitops
      name: Publishing to Resource Repository
      action: publish:gitlab
      input:
        repoUrl: "gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.component_id}}-gitops"
        #repoUrl: "gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}?owner=${{ user.entity.metadata.name }}&repo=${{parameters.component_id}}-gitops"
        #repoUrl: "gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}-gitops"
        title: gitops resources for ${{ parameters.component_id }}
        description: gitops resources for ${{ parameters.component_id }}
        sourcePath: ./tenant-gitops
        defaultBranch: main
        repoVisibility: public

    - id: create-argocd-resources
      name: Create GitOps Resources
      action: argocd:create-resources
      input:
        appName: ${{ user.entity.metadata.name }}-${{ parameters.component_id }}-bootstrap
        #appName: ${{ parameters.component_id }}-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://gitlab-gitlab.apps.${{ steps['parse-url'].output.values.base_domain }}/${{ user.entity.metadata.name }}/${{ parameters.component_id }}-gitops.git
        #repoUrl: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ user.entity.metadata.name }}/${{ parameters.component_id }}-gitops.git
        #repoUrl: https://gitlab-gitlab.apps.cluster-${{ parameters.guid }}.${{ parameters.guid }}.${{ parameters.base_domain }}/${{ parameters.repo.owner }}/${{ parameters.component_id }}-gitops.git
        path: "argocd/"

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
