# This is a simpler example showing how to add a custom rpm and set the root password

name: simple

content:
  rpms:
    - cloud-init
    - podman
    - vim

  container_images:
    - source: ${{values.registry_host}}/${{values.registry_destination}} # templated in backstage
      tag: latest
      name: localhost/app

auth:
  # "password"
  root_password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
