name: Build container images
on:
  push:
  pull_request:
    branches:
      - 'master'
jobs:
  build-devspace-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: jumpstarter-dev+summit_ci
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/jumpstarter-dev/summit-devspace
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:containers/devspace"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-exporter-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: jumpstarter-dev+summit_ci
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/jumpstarter-dev/summit-exporter
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:containers/exporter"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
