name: Build container images
on:
  push:
  pull_request:
    branches:
      - 'master'
jobs:
  build-devspace-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/devspace
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:containers/devspace"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
